### ISSUE TITLE
make problem  

### ISSUE THREAD

**Issue by YoungKang1222** [facundoolano/feedi#94]
hey great job!
When install the project ，I got the following problem:
![image](https://github.com/facundoolano/feedi/assets/30460985/df18ed70-8e5f-4bf3-8ad8-3581d5c30be1)

system: windows/ git bash

**Comment by facundoolano** [comment]
What OS and shell are you using?

(It seems like the makefile is assuming a virtualenv file that’s not there)

**Comment by YoungKang1222** [comment]
OS:windows
shell: bash(git bash in windows)

**Comment by facundoolano** [comment]
It seems like Python places the venv activate script in a different directory in Windows. I can take a look into handling both cases in the Makefile, but it may take me a while to get to it.

In the meantime, perhaps you can patch the makefile locally or run the commands manually instead of through make.

**Comment by juanbono** [comment]
@YoungKang1222 The file is probably called `activate.bat` on Windows.
